# Generated by Django 5.2 on 2026-04-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("body_markdown", models.TextField()),
                ("body_html", models.TextField(blank=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("intro", "Introduction"),
                            ("executive_summary", "Executive Summary"),
                            ("recommendation", "Macro Recommendation"),
                            ("insight", "Insights & Framing"),
                            ("small_idea", "Small Idea"),
                            ("country", "Country Profile"),
                            ("annex", "Annex"),
                            ("reference", "Reference"),
                        ],
                        max_length=30,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("meta_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="content.section",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
