# Generated by Django 5.2 on 2026-04-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("date", models.DateField()),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("country_label", models.CharField(blank=True, max_length=100)),
                ("stakeholder_name", models.CharField(max_length=200)),
                ("stakeholder_role", models.CharField(blank=True, max_length=200)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("topic_tag", models.CharField(blank=True, max_length=100)),
                ("body_markdown", models.TextField()),
                ("body_html", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
