# Generated by Django 5.2 on 2026-04-28 07:07

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_interview"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("organization", models.CharField(blank=True, max_length=300)),
                ("interview_slug", models.SlugField(max_length=200)),
                ("interview_url", models.URLField(blank=True)),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        default=content.models._new_token,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("copy_snapshot_html", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("changes_requested", "Changes requested"),
                            ("anonymized", "Anonymize requested"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("use_real_name", models.BooleanField(blank=True, null=True)),
                ("preferred_attribution", models.CharField(blank=True, max_length=300)),
                ("requested_changes", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="content_int_status_feb771_idx"
                    ),
                    models.Index(
                        fields=["interview_slug"], name="content_int_intervi_bf5d79_idx"
                    ),
                ],
            },
        ),
    ]
