# Generated by Django 5.2 on 2026-04-28 07:44

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_interviewconsent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewconsent",
            name="preferred_attribution",
        ),
        migrations.RemoveField(
            model_name="interviewconsent",
            name="requested_changes",
        ),
        migrations.RemoveField(
            model_name="interviewconsent",
            name="token",
        ),
        migrations.RemoveField(
            model_name="interviewconsent",
            name="use_real_name",
        ),
        migrations.AddField(
            model_name="interviewconsent",
            name="copy_snapshot_markdown",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interviewconsent",
            name="display_attribution",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="interviewconsent",
            name="edited_summary_markdown",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="interviewconsent",
            name="manual_outreach",
            field=models.BooleanField(
                default=False,
                help_text="Excluded from bulk email send (handled via WhatsApp etc.). Review URL still works.",
            ),
        ),
        migrations.AddField(
            model_name="interviewconsent",
            name="participation_consent",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interviewconsent",
            name="recipient_token",
            field=models.CharField(
                db_index=True, default=content.models._new_token, max_length=32
            ),
        ),
        migrations.AddField(
            model_name="interviewconsent",
            name="summary_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not yet"),
                    ("accepted", "Accepted as-is"),
                    ("edited", "Edited"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="interviewconsent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("changes_requested", "Changes requested"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="interviewconsent",
            index=models.Index(fields=["email"], name="content_int_email_57bea1_idx"),
        ),
    ]
